package com.bytedance.sdk.openadsdk.bWL;

import android.content.Context;
import android.graphics.Color;
import android.graphics.drawable.Drawable;
import android.text.TextUtils;
import android.util.AttributeSet;
import android.view.View;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.widget.SeekBar;
import com.bytedance.sdk.component.utils.pP;
import com.bytedance.sdk.openadsdk.utils.BS;
import com.bytedance.sdk.openadsdk.utils.zPa;
import com.vungle.ads.internal.presenter.MRAIDPresenter;

/* JADX INFO: compiled from: r8-map-id-84874db269549a40c0b5c7061a31fb3953e4b1b5018e77414ceb6004f20237e9 */
/* JADX INFO: loaded from: classes3.dex */
public class hp extends com.bytedance.sdk.openadsdk.core.Cc.Bc {
    public hp(Context context) {
        this(context, null);
    }

    private void IlO(Context context) {
        setId(520093726);
        setBackgroundColor(-1);
        com.bytedance.sdk.openadsdk.core.Cc.Bc bc = new com.bytedance.sdk.openadsdk.core.Cc.Bc(context);
        bc.setId(zPa.XvI);
        bc.setLayoutParams(new RelativeLayout.LayoutParams(-1, -1));
        bc.setBackgroundColor(0);
        bc.setGravity(17);
        addView(bc);
        View tVVar = new com.bytedance.sdk.openadsdk.core.Cc.tV(context);
        tVVar.setId(zPa.IRy);
        tVVar.setLayoutParams(new RelativeLayout.LayoutParams(-1, -1));
        bc.addView(tVVar);
        com.bytedance.sdk.openadsdk.core.Cc.vCE vce = new com.bytedance.sdk.openadsdk.core.Cc.vCE(context);
        vce.setId(zPa.BC);
        int iMY = BS.MY(context, 60.0f);
        RelativeLayout.LayoutParams layoutParams = new RelativeLayout.LayoutParams(iMY, iMY);
        layoutParams.addRule(13);
        vce.setLayoutParams(layoutParams);
        vce.setIndeterminateDrawable(com.bytedance.sdk.openadsdk.utils.EV.IlO(context, "tt_video_loading_progress_bar"));
        bc.addView(vce);
        com.bytedance.sdk.openadsdk.core.Cc.Cc cc = new com.bytedance.sdk.openadsdk.core.Cc.Cc(context);
        cc.setId(zPa.QfH);
        RelativeLayout.LayoutParams layoutParams2 = new RelativeLayout.LayoutParams(-2, -2);
        layoutParams2.addRule(13);
        cc.setLayoutParams(layoutParams2);
        cc.setGravity(1);
        cc.setOrientation(1);
        cc.setVisibility(8);
        bc.addView(cc);
        com.bytedance.sdk.openadsdk.core.Cc.tV tVVar2 = new com.bytedance.sdk.openadsdk.core.Cc.tV(context);
        tVVar2.setId(zPa.Os);
        tVVar2.setLayoutParams(new LinearLayout.LayoutParams(-2, -2));
        tVVar2.setImageDrawable(com.bytedance.sdk.openadsdk.utils.EV.IlO(context, "tt_refreshing_video_textpage"));
        ImageView.ScaleType scaleType = ImageView.ScaleType.CENTER;
        tVVar2.setScaleType(scaleType);
        cc.addView(tVVar2);
        com.bytedance.sdk.openadsdk.core.Cc.lEW lew = new com.bytedance.sdk.openadsdk.core.Cc.lEW(context);
        lew.setId(zPa.KS);
        lew.setLayoutParams(new LinearLayout.LayoutParams(-2, -2));
        lew.setText(pP.IlO(context, "tt_video_retry_des_txt"));
        lew.setTextColor(Color.parseColor("#999999"));
        cc.addView(lew);
        com.bytedance.sdk.openadsdk.core.Cc.tV tVVar3 = new com.bytedance.sdk.openadsdk.core.Cc.tV(context);
        tVVar3.setId(zPa.xJ);
        RelativeLayout.LayoutParams layoutParams3 = new RelativeLayout.LayoutParams(-2, -2);
        layoutParams3.addRule(13);
        tVVar3.setLayoutParams(layoutParams3);
        tVVar3.setScaleType(scaleType);
        tVVar3.setImageDrawable(com.bytedance.sdk.openadsdk.utils.EV.IlO(context, "tt_play_movebar_textpage"));
        tVVar3.setVisibility(8);
        addView(tVVar3);
        com.bytedance.sdk.openadsdk.core.Cc.tV tVVar4 = new com.bytedance.sdk.openadsdk.core.Cc.tV(context);
        tVVar4.setId(zPa.CQo);
        int iMY2 = BS.MY(context, 30.0f);
        RelativeLayout.LayoutParams layoutParams4 = new RelativeLayout.LayoutParams(iMY2, iMY2);
        layoutParams4.addRule(21);
        layoutParams4.addRule(11);
        int iMY3 = BS.MY(context, 7.0f);
        layoutParams4.setMarginEnd(iMY3);
        layoutParams4.rightMargin = iMY3;
        layoutParams4.topMargin = iMY3;
        tVVar4.setLayoutParams(layoutParams4);
        tVVar4.setBackground(com.bytedance.sdk.openadsdk.utils.EV.IlO(context, "tt_detail_video_btn_bg"));
        tVVar4.setScaleType(scaleType);
        tVVar4.setImageDrawable(com.bytedance.sdk.openadsdk.utils.EV.IlO(context, "tt_close_move_detail"));
        addView(tVVar4);
        com.bytedance.sdk.openadsdk.core.Cc.lEW lew2 = new com.bytedance.sdk.openadsdk.core.Cc.lEW(context);
        lew2.setId(zPa.qyG);
        RelativeLayout.LayoutParams layoutParams5 = new RelativeLayout.LayoutParams(-1, -2);
        layoutParams5.addRule(9);
        layoutParams5.addRule(20);
        layoutParams5.addRule(10);
        lew2.setLayoutParams(layoutParams5);
        lew2.setBackground(com.bytedance.sdk.openadsdk.utils.EV.IlO(context, "tt_video_black_desc_gradient"));
        TextUtils.TruncateAt truncateAt = TextUtils.TruncateAt.END;
        lew2.setEllipsize(truncateAt);
        lew2.setMaxLines(2);
        int iMY4 = BS.MY(context, 15.0f);
        lew2.setPadding(iMY4, BS.MY(context, 14.0f), iMY4, 0);
        lew2.setSingleLine(false);
        lew2.setTextColor(-1);
        lew2.setTextSize(2, 17.0f);
        lew2.setVisibility(8);
        addView(lew2);
        com.bytedance.sdk.openadsdk.core.Cc.Bc bc2 = new com.bytedance.sdk.openadsdk.core.Cc.Bc(context);
        bc2.setId(zPa.Fv);
        RelativeLayout.LayoutParams layoutParams6 = new RelativeLayout.LayoutParams(-1, -2);
        layoutParams6.addRule(10);
        bc2.setLayoutParams(layoutParams6);
        bc2.setBackground(com.bytedance.sdk.openadsdk.utils.EV.IlO(context, "tt_video_black_desc_gradient"));
        bc2.setGravity(16);
        bc2.setVisibility(8);
        addView(bc2);
        com.bytedance.sdk.openadsdk.core.Cc.tV tVVar5 = new com.bytedance.sdk.openadsdk.core.Cc.tV(context);
        int i2 = zPa.ct;
        tVVar5.setId(i2);
        RelativeLayout.LayoutParams layoutParams7 = new RelativeLayout.LayoutParams(-2, -1);
        layoutParams7.addRule(15);
        int iMY5 = BS.MY(context, 12.0f);
        layoutParams7.leftMargin = iMY5;
        layoutParams7.setMarginStart(iMY5);
        tVVar5.setLayoutParams(layoutParams7);
        tVVar5.setScaleType(scaleType);
        tVVar5.setImageDrawable(com.bytedance.sdk.openadsdk.utils.EV.IlO(context, "tt_leftbackbutton_titlebar_photo_preview"));
        bc2.addView(tVVar5);
        com.bytedance.sdk.openadsdk.core.Cc.lEW lew3 = new com.bytedance.sdk.openadsdk.core.Cc.lEW(context);
        lew3.setId(zPa.NI);
        RelativeLayout.LayoutParams layoutParams8 = new RelativeLayout.LayoutParams(-2, -1);
        layoutParams8.addRule(15);
        int iMY6 = BS.MY(context, 16.0f);
        layoutParams8.leftMargin = iMY6;
        layoutParams8.rightMargin = iMY;
        layoutParams8.setMarginStart(iMY6);
        layoutParams8.setMarginEnd(iMY);
        layoutParams8.addRule(17, i2);
        int i8 = zPa.dM;
        layoutParams8.addRule(0, i8);
        layoutParams8.addRule(1, i2);
        layoutParams8.addRule(16, i8);
        lew3.setLayoutParams(layoutParams8);
        lew3.setEllipsize(truncateAt);
        lew3.setGravity(16);
        lew3.setMaxLines(1);
        lew3.setSingleLine(true);
        lew3.setTextColor(-1);
        lew3.setTextSize(2, 17.0f);
        bc2.addView(lew3);
        com.bytedance.sdk.openadsdk.core.Cc.Cc cc2 = new com.bytedance.sdk.openadsdk.core.Cc.Cc(context);
        cc2.setId(i8);
        RelativeLayout.LayoutParams layoutParams9 = new RelativeLayout.LayoutParams(-2, -2);
        layoutParams9.addRule(21);
        layoutParams9.addRule(11);
        int iMY7 = BS.MY(context, 14.0f);
        layoutParams9.rightMargin = iMY7;
        layoutParams9.setMarginEnd(iMY7);
        cc2.setLayoutParams(layoutParams9);
        cc2.setGravity(16);
        cc2.setOrientation(1);
        bc2.addView(cc2);
        com.bytedance.sdk.openadsdk.core.Cc.lEW lew4 = new com.bytedance.sdk.openadsdk.core.Cc.lEW(context);
        lew4.setId(zPa.TU);
        LinearLayout.LayoutParams layoutParams10 = new LinearLayout.LayoutParams(-2, -2);
        layoutParams10.gravity = 1;
        lew4.setLayoutParams(layoutParams10);
        lew4.setGravity(16);
        lew4.setMaxLines(1);
        lew4.setSingleLine(true);
        lew4.setTextColor(-1);
        lew4.setTextSize(2, 12.0f);
        cc2.addView(lew4);
        com.bytedance.sdk.openadsdk.core.Cc.Cc cc3 = new com.bytedance.sdk.openadsdk.core.Cc.Cc(context);
        cc3.setId(zPa.BK);
        RelativeLayout.LayoutParams layoutParams11 = new RelativeLayout.LayoutParams(-2, BS.MY(context, 40.0f));
        layoutParams11.addRule(12);
        layoutParams11.addRule(21);
        layoutParams11.addRule(11);
        cc3.setLayoutParams(layoutParams11);
        cc3.setGravity(16);
        cc3.setOrientation(0);
        cc3.setVisibility(8);
        addView(cc3);
        com.bytedance.sdk.openadsdk.core.Cc.lEW lew5 = new com.bytedance.sdk.openadsdk.core.Cc.lEW(context);
        lew5.setId(zPa.XfO);
        LinearLayout.LayoutParams layoutParams12 = new LinearLayout.LayoutParams(-2, -2);
        layoutParams12.leftMargin = iMY6;
        layoutParams12.rightMargin = iMY5;
        layoutParams12.setMarginEnd(iMY5);
        layoutParams12.setMarginStart(iMY6);
        lew5.setLayoutParams(layoutParams12);
        lew5.setText(pP.IlO(context, "tt_00_00"));
        lew5.setTextColor(-1);
        lew5.setTextSize(2, 10.0f);
        cc3.addView(lew5);
        SeekBar seekBar = new SeekBar(context);
        seekBar.setId(zPa.IK);
        LinearLayout.LayoutParams layoutParams13 = new LinearLayout.LayoutParams(0, BS.MY(context, 5.0f));
        layoutParams13.gravity = 16;
        seekBar.setLayoutParams(layoutParams13);
        seekBar.setMax(100);
        seekBar.setPadding(0, 0, 0, 0);
        seekBar.setProgressDrawable(com.bytedance.sdk.openadsdk.utils.EV.IlO(context, "tt_seek_progress"));
        seekBar.setThumb(com.bytedance.sdk.openadsdk.utils.EV.IlO(context, "tt_seek_thumb"));
        seekBar.setThumbOffset(0);
        cc3.addView(seekBar);
        com.bytedance.sdk.openadsdk.core.Cc.lEW lew6 = new com.bytedance.sdk.openadsdk.core.Cc.lEW(context);
        lew6.setId(zPa.Ct);
        LinearLayout.LayoutParams layoutParams14 = new LinearLayout.LayoutParams(-2, -2);
        layoutParams14.leftMargin = iMY5;
        layoutParams14.rightMargin = iMY6;
        layoutParams14.setMarginEnd(iMY6);
        layoutParams14.setMarginStart(iMY5);
        lew6.setLayoutParams(layoutParams14);
        lew6.setText(pP.IlO(context, "tt_00_00"));
        lew6.setTextColor(-1);
        lew6.setTextSize(2, 10.0f);
        cc3.addView(lew6);
        com.bytedance.sdk.openadsdk.core.Cc.tV tVVar6 = new com.bytedance.sdk.openadsdk.core.Cc.tV(context);
        tVVar6.setId(zPa.hHv);
        tVVar6.setLayoutParams(new LinearLayout.LayoutParams(-2, -1));
        tVVar6.setPadding(iMY6, 0, iMY6, 0);
        tVVar6.setScaleType(scaleType);
        tVVar6.setVisibility(8);
        tVVar6.setImageDrawable(pP.EO(context, "tt_enlarge_video"));
        cc3.addView(tVVar6);
        View rpVar = new rp(context);
        rpVar.setId(zPa.NST);
        rpVar.setLayoutParams(new RelativeLayout.LayoutParams(-1, -1));
        addView(rpVar);
        com.bytedance.sdk.openadsdk.core.Cc.lEW lew7 = new com.bytedance.sdk.openadsdk.core.Cc.lEW(context);
        lew7.setId(zPa.LT);
        RelativeLayout.LayoutParams layoutParams15 = new RelativeLayout.LayoutParams(-2, -2);
        layoutParams15.leftMargin = iMY5;
        layoutParams15.addRule(9);
        layoutParams15.addRule(20);
        lew7.setLayoutParams(layoutParams15);
        lew7.setBackgroundColor(Color.parseColor("#00000000"));
        lew7.setText(MRAIDPresenter.CLOSE);
        lew7.setMinHeight(BS.MY(context, 44.0f));
        lew7.setCompoundDrawablesWithIntrinsicBounds(com.bytedance.sdk.openadsdk.utils.EV.IlO(context, "tt_shadow_btn_back"), (Drawable) null, (Drawable) null, (Drawable) null);
        addView(lew7);
    }

    public hp(Context context, AttributeSet attributeSet) {
        this(context, attributeSet, 0);
    }

    public hp(Context context, AttributeSet attributeSet, int i2) {
        super(context, attributeSet, i2);
        IlO(context);
    }
}
